accepted = [
    "Zlib",
    "BSL-1.0",
    "MIT",
    "ISC",
    "Unicode-3.0",
    "OFL-1.1",
    "Ubuntu-font-1.0",
    "Apache-2.0",
    "GPL-3.0",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
no-clearly-defined = true

