[workspace]
resolver = "3"
members = [
    "garlicjr",
    "garlicjr_dbg",
]

[workspace.package]
authors = ["notskm"]
license = "GPL-3.0-or-later"
edition = "2024"
rust-version = "1.87"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
opt-level = 2
