[package]
name = "garlicjr"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dev-dependencies]
rstest = "0.21.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
